name: Deploy

on: [push]
  # push:
  #   branches:
  #     - deploy

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push elixir:1.18-otp-28-debian
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          file: elixir-debian.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: mikaak/elixir:1.18-otp-28-debian

      - name: Build and push elixir-node:1.18-otp-28-debian
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          file: node-elixir-debian.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: mikaak/elixir-node:1.18-otp-28-debian

      - name: Build and push elixir-terraform-ansible-builder:1.18-otp-28-debian
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          file: elixir-debian-terraform-ansible.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: mikaak/elixir-terraform-ansible-builder:1.18-otp-28-debian
